# Travic-CI-Config file for \Org\Heigl\Hyphenator
#
language: php
php:
  - "5.4"
  - "5.3"
  - "5.5"
  - "hhvm"

matrix:
  allow_failures:
    - hhvm: *
  fast_finish : true
  
script: phpunit --coverage-text