# Travic-CI-Config file for \Org\Heigl\Hyphenator
#
sudo: false
language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly
  - nightly

matrix:
  fast_finish : true
  allow_failures:
      - php: 5.3
      - php: 5.4
      - php: hhvm-nightly
      - php: nightly
  
script:
  - composer update
  - phpunit --coverage-text